export const ELECTRIC_VEHICLE_AVAILABILITY = "No vehicle available"
export const ADD_VEHICLE_BUTTON = "Add Electric Vehicle"
export const SEARCH_PLACEHOLDER = "Search by reg. number or model"
export const SELECT_VEHICLE_BTN = "Select Vehicle"
export const CAR_MODEL = "Car Model"
export const CAR_VIN = "Car Vin"
export const CAR_NAME = "Car Name"
export const CAR_PRICE = "Car Price"
